version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_TYPE=vicuna_ggml
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
