name: mlc-prebuilt
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=4.8.0=pyhd8ed1ab_0
  - arrow-cpp
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - blas=1.0=mkl
  - boost-cpp
  - bottleneck
  - brotli-python
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates
  - certifi
  - clang=14.0.6
  - clang-14=14.0.6
  - colorama=0.4.6
  - cpuonly
  - datasets
  - deprecated=1.2.13
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - freetype=2.12.1
  - frozenlist=1.5.0
  - gflags=2.2.2
  - giflib=5.2.2
  - git
  - git-lfs=3.6.1
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - greenlet=3.1.1
  - h11=0.14.0
  - huggingface_hub=0.24.6
  - importlib-metadata=7.0.1
  - iniconfig=1.1.1
  - intel-openmp
  - jinja2=3.1.5
  - joblib
  - jpeg
  - jsonpatch=1.33
  - jsonpointer=2.1
  - langchain-huggingface=0.1.2
  - langdetect=1.0.9
  - langsmith=0.1.147
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang-cpp=14.0.6
  - libcurl=8.12.1
  - libdeflate=1.22
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgrpc=1.62.2
  - libjpeg-turbo=2.0.0
  - liblzma=5.6.4
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsqlite
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuv=1.48.0
  - libvulkan-loader=1.3.296.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - miktex
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - openjpeg=2.5.2
  - openssl=3.4.1
  - orc=2.0.1
  - orjson=3.10.14
  - packaging=24.2
  - pandas
  - pillow
  - pip
  - pluggy=1.5.0
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.11.8
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - pytorch
  - pytorch-mutex=1.0=cpu
  - pyyaml
  - re2=2022.04.01
  - regex=2024.11.6
  - requests
  - requests-toolbelt=1.0.0
  - scikit-learn
  - sentence-transformers
  - setuptools=72.1.0
  - sleef=3.5.1
  - snappy=1.2.1
  - sqlalchemy=2.0.37
  - sqlite>=3.40.0
  - sse-starlette=2.2.1
  - starlette=0.45.3
  - tbb=2021.8.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchaudio
  - torchvision
  - tqdm
  - typing-extensions=4.12.2
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - wrapt=1.17.0
  - xxhash=0.8.0
  - xz
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib
  - zstd
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - asgiref==3.8.1
      - attrs==25.1.0
      - backoff==2.2.1
      - bcrypt==4.2.1
      - build==1.2.2.post1
      - cachetools==5.5.1
      - charset-normalizer==3.4.1
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.3
      - click==8.1.8
      - click-default-group==1.2.4
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - coverage==7.6.12
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - decorator==5.1.1
      - diskcache==5.6.3
      - distro==1.9.0
      - docopt==0.6.2
      - durationpy==0.9
      - fastapi
      - filelock==3.17.0
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fsspec==2024.12.0
      - google-auth==2.38.0
      - googleapis-common-protos==1.67.0
      - grpcio==1.70.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub
      - humanfriendly==10.0
      - idna==3.10
      - importlib-resources==6.5.2
      - inform==1.33
      - jiter==0.8.2
      - kiwisolver==1.4.8
      - kubernetes==32.0.1
      - langchain
      - langchain-chroma
      - langchain-community
      - langchain-core
      - langchain-text-splitters==0.3.6
      - llm==0.22
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - matplotlib
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mlc-python
      - mmh3==5.1.0
      - monotonic==1.6
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - numpy
      - oauthlib==3.2.2
      - onnxruntime==1.20.1
      - openai==1.63.2
      - opencv-python==4.11.0.86
      - opentelemetry-api==1.30.0
      - opentelemetry-exporter-otlp-proto-common==1.30.0
      - opentelemetry-exporter-otlp-proto-grpc==1.30.0
      - opentelemetry-instrumentation==0.51b0
      - opentelemetry-instrumentation-asgi==0.51b0
      - opentelemetry-instrumentation-fastapi==0.51b0
      - opentelemetry-proto==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - opentelemetry-util-http==0.51b0
      - overrides==7.7.0
      - posthog==3.14.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==7.0.0
      - puremagic==1.28
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.11.0a2
      - pydantic-core==2.29.0
      - pydantic-settings==2.7.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - python-ulid==3.0.0
      - pytz==2025.1
      - quantiphy==2.20
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rsa==4.9
      - safetensors==0.5.2
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - sniffio==1.3.1
      - sqlite-fts4==1.0.3
      - sqlite-migrate==0.1b0
      - sqlite-utils==3.38
      - sympy==1.13.1
      - tabulate==0.9.0
      - tiktoken==0.9.0
      - timm==1.0.15
      - tokenizers==0.21.0
      - torch
      - tornado==6.4.2
      - transformers
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - ultralytics==8.3.78
      - ultralytics-thop==2.0.14
      - uvicorn
      - watchfiles==1.0.4
      - wcwidth==0.2.13
      - websocket-client==1.8.0
      - websockets==15.0
      - yarl==1.18.3
