name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build mlc_llm from source
        run: |
          # Clone the mlc-llm repo recursively to get all submodules
          git clone --recursive https://github.com/mlc-ai/mlc-llm.git
          cd mlc-llm
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          # Export the build directory to LD_LIBRARY_PATH so the shared library can be found
          echo "LD_LIBRARY_PATH=$(pwd)" >> $GITHUB_ENV
          cd ../python
          pip install .

      - name: Install Python dependencies
        env:
          # Append the mlc_llm build directory to the LD_LIBRARY_PATH
          LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}:${{ github.workspace }}/mlc-llm/build
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
