name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            git \
            cmake \
            build-essential \
            cargo \
            libtinfo-dev \
            libedit-dev \
            libgl1 \
            libglib2.0-0 \
          && sudo rm -rf /var/lib/apt/lists/*

      - name: Install Python dependencies for building TVM
        run: |
          pip install --upgrade pip
          pip install cython

      - name: Install Rust via rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "/home/runner/.cargo/bin" >> $GITHUB_PATH

      - name: Build TVM from source
        run: |
          git clone --recursive https://github.com/apache/tvm.git tvm
          cd tvm
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          echo "PYTHONPATH=$(pwd)/../python" >> $GITHUB_ENV

      - name: Build and install mlc_llm from source
        run: |
          git clone --recursive https://github.com/mlc-ai/mlc-llm.git
          cd mlc-llm
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          echo "LIBMLC_LLM_PATH=$(pwd)" >> $GITHUB_ENV
          # Now install the Python package so that "from mlc_llm import MLCEngine" works:
          cd ../python && pip install .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q --ignore=mlc-llm
