name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-mlc-llm-app .

      - name: Run container in detached mode
        run: |
          docker run -d --name mlc_app -p 8000:8000 my-mlc-llm-app
          # Give the app some time to start
          sleep 10

      - name: Check health endpoint
        run: |
          curl --fail http://localhost:8000/health

      - name: Run tests inside container
        run: |
          # Adjust the test command as needed (for example, if you use pytest)
          docker exec mlc_app pytest --maxfail=1 --disable-warnings -q

      - name: Stop and remove container
        run: |
          docker stop mlc_app
          docker rm mlc_app
